services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - /data:/var/lib/postgresql/data
    # networks:
    #   - myfastapi
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
  api:
    container_name: myfastapi
    image: myfastapi
    # networks:
    #   - myfastapi
    ports:
      - "80:80"
    depends_on:
      - db
